export const tablesTableData = [
  {
    name: "Esthera Jackson",
    phone: "alexa@simmmple.com",
    subdomain: "Sick, Throat, Headache",
    domain: "Fever",
    status: "Today",
    date: "14/06/21 07:00:00",
  },
  {
    name: "Alexa Liras",
    phone: "laurent@simmmple.com",
    subdomain: "Sick, Throat, Headache",
    domain: "Fever",
    status: "Incomming",
    date: "12/05/21 07:00:00",
  },
  {
    name: "Laurent Michael",
    phone: "laurent@simmmple.com",
    subdomain: "Sick, Throat, Headache",
    domain: "Fever",
    status: "Today",
    date: "07/06/21 07:00:00",
  },
  {
    name: "Freduardo Hill",
    phone: "freduardo@simmmple.com",
    subdomain: "Sick, Throat, Headache",
    domain: "Fever",
    status: "Today",
    date: "14/11/21 07:00:00",
  },
  {
    name: "Daniel Thomas",
    phone: "daniel@simmmple.com",
    subdomain: "Sick, Throat, Headache",
    domain: "Fever",
    status: "Incomming",
    date: "21/01/21 07:00:00",
  },
  {
    name: "Mark Wilson",
    phone: "mark@simmmple.com",
    subdomain: "Sick, Throat, Headache",
    domain: "/UX Design",
    status: "Incomming",
    date: "04/09/20 07:00:00",
  },
];